#!/usr/bin/env bash

cp /autograder/submission/movies.py /autograder/source/movies.py
cp /autograder/source/data/*.csv /autograder/source/

cd /autograder/source

TEMP_REPORT=/autograder/results/pytestout.json
FINAL_REPORT=/autograder/results/results.json

#python3.9 -m pytest tests/test_*.py -p no:warnings --json-report --json-report-file $TEMP_REPORT
#python3.9 convert_results.py $TEMP_REPORT $FINAL_REPORT
python3 -m pytest tests/test_*.py -p no:warnings --json-report --json-report-file $TEMP_REPORT
python3 convert_results.py $TEMP_REPORT $FINAL_REPORT
