= Exercise: Time Conversion
:includedir: ../../../../includes
:source-highlighter: rouge
:stem:
:toc: left

== Background and instructions

In many parts of the world, it's common to use a 24-hour system to tell time, where 0:00 is midnight, 12:00 is noon, 13:00 is 1pm, etc. For this exercise, you will use the template below to create a script that does some simple conversion from 24-hour to 12-hour formats. You will write a function called `convert_times()` that takes a list of hours in 24-hour format (in other words, integers between 0 and 23, inclusive) and returns a corresponding list of strings consisting of an hour in 12-hour format and a time of day expression, using the table below:

[%autowidth]
[%header, cols=2*,stripes=even]
|===
|Time range (hours)
|Time of day expression

|0
|midnight

|1&ndash;11
|in the morning

|12
|noon

|13&ndash;16
|in the afternoon

|17&ndash;20
|in the evening

|21&ndash;23
|at night
|===

For example, `convert_times([0, 10, 20])` should evaluate to `["12 midnight", "10 in the morning", "8 in the evening"]`.

Use f-strings to generate your list of strings. Remember that 0 in 24-hour time corresponds to 12 in 12-hour time.

Your function should have a docstring that briefly states

* what the function does
* what argument(s) it requires
* what kind of value it returns and what this value means

Remember that a function docstring should be the first statement in the body of your function.

=== Template

The template code is designed to take one or more integers as link:https://realpython.com/python-command-line-arguments/[command-line arguments]. It validates these arguments, converts them to integers, invokes your function, and prints separate lines for each value in the list returned by your function. See <<Running your program>> for an example of how you might run your program and what output you should expect.

.Template
[source,python]
----
include::time_conversion.py[]
----

== Running your program

To run your program, open a terminal and ensure you are in the directory where your script is saved. At the command prompt, type `python3` (Windows users, type `python` instead) followed by a space, the name of your script, another space, and one or more integers between 0 and 23, separated by spaces. For example, if your script were called `time_conversion.py` and you wanted to convert the hours 0, 9, 14, and 19, you would type

----
python3 time_conversion.py 0 9 14 19
----

In this case, the script should print the following in the terminal:

----
0 in 24-hour time is 12 midnight
9 in 24-hour time is 9 in the morning
14 in 24-hour time is 2 in the evening
19 in 24-hour time is 7 in the evening
----

The template code will take care of printing for you. Your function should not contain any `print()` statements; it should return a list of strings as described under <<Background and instructions>>.

== Testing

You can use the script link:test_time_conversion.py[] to test your solution. Make sure you have Pytest installed and that your script and `test_time_conversion.py` are in the same directory on your computer. Edit line 4 of `test_time_conversion.py` so that it contains the name of your script (without the `.py` ending).

To use the test script, open a terminal and navigate to the directory containing your script and `test_time_conversion.py`. Then type the following at the command prompt:

----
pytest test_time_conversion.py
----
