= Exercise: Testing Reverse Polish Notation
:includedir: ../../../../includes
:source-highlighter: rouge
:stem:
:toc: left

== Background

Last week we wrote a program to interpret expressions in reverse Polish notation. This week we will write unit tests to test the `evaluate()` function from last week's program. As a reminder, that function takes one argument (a string containing a postfix expression) and returns the result of the expression as a float.

== Problem statement

Write a Pytest test script that imports and tests the `evaluate()` function of the program you wrote last week.

== Instructions

At the start of your test script, import your solution to the reverse Polish notation problem. (If you don't have a solution, you can download the solution we wrote in class on Friday: link:https://umd.instructure.com/courses/1299872/assignments/5527314?module_item_id=10549193[].)

We are assuming the `evaluate()` function was not written to handle invalid input, so all test cases must use valid postfix expressions as input. Write one or more test functions that collectively cover the following cases:

* Edge cases
** An expression that consists of a single integer
** An expression that consists of a single float
** An expression that consists of a negative number
** An expression that consists of a two-digit number
* Happy path cases
** An expression that performs addition
** An expression that performs subtraction
** An expression that performs multiplication
** An expression that performs division
** An expression consisting of three numbers followed by two different operators
** An expression consisting of two numbers, an operator, a third number, and another operator

__Hint: because `evaluate()` returns a float, your tests should test for values close to the expected result (as opposed to values that are exactly equal to the expected result). One way to do this is with `math.isclose()`; another is with `pytest.approx()`.__

== Installing Pytest

Before you can run your script, you must have installed Pytest. If you have already installed Pytest, you can skip this section. If you have not yet installed Pytest, do so by typing the following at the terminal (Windows users, replace `python3` with `python`):

----
python3 -m pip install --upgrade pip
python3 -m pip install --upgrade pytest
----

== Running your test script

Your test script should be saved in the same directory as the solution to the reverse Polish notation script. Ensure that VS Code is opened to that directory. Then open the terminal by pressing Ctrl+{blank}+++`+++ or going to the View menu and selecting Terminal. The following example shows how to run a test script called `test_rpn.py`; replace this with the name of your script.

----
pytest test_rpn.py
----

If that doesn't work, try the following (Windows users, replace `python3` with `python`):

----
python3 -m pytest test_rpn.py
----

== General instructions for exercises

Exercises are meant to be completed in class on Wednesdays. You should have received an email with a Zoom URL for your Wednesday exercise group. Your group will have a different facilitator each week. The facilitator will assign you to work in partnerships of two or three people.

Designate one person in your partnership to be the driver for the session; the other partner(s) will be navigator(s) for the session. The driver should share their screen; they will do the typing. The navigator should look over what the driver types and provide suggestions and feedback. The driver and navigator should be talking through the problem-solving process throughout the session. Both driver and navigator will be graded on their active participation in the programming process.

If you need clarification or help, press the Help button at the bottom of your Zoom window. Your facilitator will join your breakout room as soon as possible. Be patient; other partnerships may have asked for help ahead of you. Do your best to work through issues while you wait for your facilitator to arrive.

If you finish before the end of class, try to get your facilitator to review your solution and give you feedback. If you do not finish by the end of class, you will have another day to complete the exercise and turn it in. You may work with your partner out of class to finish the assignment, or you may complete it on your own. You may not complete the assignment on your own and then share the completed assignment with your partner.

At the end of class, the driver should email the solution to their partner(s), whether it is complete or not. Each member of a partnership is responsible to submit their own solution. Students who for whatever reason fail to submit will not receive credit for their partner's submission. It is your responsibility to submit your own solution on time and to verify that your submission was successfully uploaded.

== Academic integrity

This assignment may be completed with a partner from class as long as both partners are actively involved in the problem solving process. This assignment is to be completed without outside help of any kind (including, but not limited to, help from tutors or the internet). Disseminating these instructions in whole or in part without written permission of the instructor is considered an infraction of academic integrity.
