= Exercise: Electoral College
:includedir: ../../../../includes
:source-highlighter: rouge
:stem:
:toc: left

== Background

The United States Electoral College is the official government body that determines who will be the president of the United States. Each state gets one elector for each senator and representative it has in the US Congress. The District of Columbia also gets three electors. All states except Maine and Nebraska have laws that stipulate that electors must vote for the candidate who received the most votes in their state. (For this exercise, we will pretend that Maine and Nebraska work this way, too.)

For this assignment, you will write an electoral college calculator. You'll work with two dictionaries, built from data in two separate text files. One dictionary will indicate the number of electors per state; the other will assign a hypothetical winning party ("R" or "D") to each state. You'll use those two dictionaries to determine who would win a presidential election based on the outcome of voting in each state. By modifying the contents of the file that assigns a party to each state, you can experiment with different potential outcomes. (The initial outcomes listed in the file are the outcomes of the 2016 presidential election.)

== Instructions

Using the `electoral_college.py` template (see below), write a function called `get_winner()` with two parameters: a dictionary of electors and a dictionary of hypothetical outcomes. Both dictionaries will have the names of states as their keys. The dictionary of electors will have integer values (the number of electors by state). The dictionary of potential outcomes will have either "R" or "D" as its values. Your function should calculate the number of electoral votes received by each candidate ("R" or "D") and return a tuple consisting of the winning candidate and total number of electoral votes that candidate received.

Your function should have a docstring that briefly states

* what the function does
* what argument(s) it requires
* what kind of value it returns and what this value means

Remember that a function docstring should be the first statement in the body of your function.

== Template

.electoral_college.py
[source, python]
----
include::electoral_college.py[]
----
