= Exercise: Word Value
:includedir: ../../../../includes
:source-highlighter: rouge
:stem:
:toc: left

== Background

When I was in 6th grade, my math teacher assigned me to find a list of "dollar words". If you pretend that the letter "a" is worth a penny, the letter "b" is worth two cents, and so on until you get to the letter "z", which is worth twenty-six cents, you can convert each letter in a word into a value and then sum the values of all the letters in the word to get the "value" of the word. If the sum happens to be 100 cents, you have found a dollar word.

Finding dollar words by hand is a pointless exercise at any grade level and not remotely educational. In this exercise, you'll write the tool I wish I had back in the day: a class called `WordValue` that reads in a list of words from a file, builds a dictionary that maps words to values, and has the ability to pull out all words of a specified value (such as 100).

The primary goal of this exercise is to practice comprehensions and generator expressions.

== Instructions

Use the supplied template, `word_value.py`. Replace the comment on line 9 with your implementation of the `WordValue` class. Follow the directions below as you implement your class.

=== What the methods do

The `+++__init__()+++` method defines the attribute `words`, which will map words from a file onto values (for example, `"cab"` would have the value `6`; `"day"` would have the value `30`).

The `appraise_word()` method calculates the value of a word.

The `words_by_value()` method returns all keys from the `words` attribute whose value is the specified value. (For example, if `words_by_value(6)` would return a list that includes "cab", if "cab" is one of the keys in `self.words`.)

=== `+++__init__()+++` method

Define an `+++__init__()+++` method with two parameters:

* `self`
* `filename`: a string containing the path to a file of words that you will read in

Open `filename` for reading. Use a dictionary comprehension to define an attribute called `words`:

* Each key in `words` will be a line from the file, with whitespace stripped off.
* Each value in `words` will be the result of the `appraise_word()` method as applied to the line (see below).

=== `appraise_word()` method

Define an `appraise_word()` method with two parameters:

* `self`
* `word`: a string to convert to a value.

Convert `word` to lower case. Use a generator expression to assign a value to each letter in `word`; ignore (filter out) any characters that are not letters between "a" and "z". Return the sum of the values in your generator.

There are several different ways that you could assign values to letters (you only need to do it one way):

* You could make a dictionary mapping letters onto numbers. If you use this method, you would ignore characters that aren't in your dictionary.
* You could make a string with all the letters in order, find the index of each letter you are interested in, and add 1 to it; in this case, you would ignore characters that aren't in your string.
* You could use the `ord()` function to convert letters to integers. `ord()` takes a one-character string as an argument and returns the code point of that character. You can assume that code points are sequential (in other words, the code point of "a" is one less than the code point of "b", etc.), but you would need to do a little subtraction to get from `ord("a")` to 1, from `ord("z")` to 26, etc. If you use this method, you would ignore characters whose code points are not between the code points of "a" and "z".

=== `words_by_value()` method

Define a `words_by_value()` method with two parameters:

* `self`
* `value`: a value to find corresponding words for.

Use a list comprehension to return all words in your object's `words` attribute whose value is `value`. (In other words, filter the keys of `words` so that you keep only keys whose corresponding value is `value`).

=== Docstrings

Write a class docstring that explains the purpose of the class and documents the data type and purpose of any attributes.

Write method docstrings for `+++__init__()+++`, `appraise_word()`, and `words_by_value()`.

* Each method docstring should explain the purpose of the method and the data type and purpose of each parameter (except for self).
* If the method returns a value, document the data type and purpose of the return value.
* If the method has side effects, document them.

== Test file

A sample word file, `words`, is provided for you.

== Running your script

Your script can run in either "interactive" or "batch" mode. To use batch mode, you specify a value using the "-v" command-line argument. The program will print all words of that value for you. To use interactive mode, use the "-i" command-line argument. The program will ask you to enter values and will print the words that correspond to those values.

Here's a complete example of how you might run your program in batch mode. It assumes your file is called `word_vaue.py` and that the file `words` is in the same directory. (Windows users, replace "python3" with "python".)

----
python3 word_value.py words -v 100
----

Here's how you would run your program in interactive mode:

----
python3 word_value.py words -i
----
