= Exercise: Testing rock, paper, scissors, fire, water
//:stylesdir: ../../css
//:stylesheet: page.css
:includedir: ../../../includes
:source-highlighter: rouge
:stem:
:toc: left

== Background

Rock, paper, scissors, fire, water{blank}footnote:[https://en.wikipedia.org/wiki/Rock_paper_scissors#Game-theoretic_variations] is a variant of the classic game rock, paper, scissors. Game play is simple: on the count of three, two players each make a hand shape representing one of the five items. If the two players both selected the same item, the game ends in a draw; otherwise, the winner is chosen based on the rules in the table below.

.Rock, Paper, Scissors, Fire, Water
[%autowidth]
|===
|Item |Defeats |Is defeated by

|paper
|rock, water
|scissors, fire

|rock
|scissors, water
|paper, fire

|scissors
|paper, water
|rock, fire

|fire
|paper, rock, scissors
|water

|water
|fire
|rock, paper, scissors
|===

You have been provided with two versions of a program that determines the winner of this game. One version should work properly; the other has some bugs. Both versions of the program have a function called `rpsfw()`; the header and docstring of this function are provided below:

[source,python]
----
def rpsfw(item1, item2):
    """ Determine the winner of a game of rock, paper, scissors, fire, water.
    
    Args:
        item1 (str): one of the following strings: "rock", "paper", "scissors",
            "fire", or "water".
        item2 (str): another of the five strings mentioned above. May or may not
            be identical to item1.
    
    Returns:
        int: 0 if a tie, 1 if item1 defeats item2, or 2 if item2 defeats item1.
    """
----

== Problem statement

Write a script to test the `rpsfw()` function described above.

== Instructions

At the start of your test script, import the `rpsfw()` function from one of the two scripts.

